"""Contrato de datos del Agente API (ApiArtifact v1.0.0)."""

from ai.agents.arquitectura.schemas.enums import RiskSeverity
from ai.agents.bd.schemas.enums import LogicalType
from ai.agents.ef.schemas.enums import Audience, HttpMethod, Origin, QuestionStatus

from .artifact import (
    OPENAPI_VERSION,
    SCHEMA_VERSION,
    ApiAnalysis,
    ApiArtifact,
    ApiMetrics,
    ApiRuleMapping,
    ApiSchema,
    AuthConfig,
    AuthorizationRule,
    Conventions,
    Coverage,
    Endpoint,
    ErrorEntry,
    OpenApiDocument,
    PaginationConfig,
    Parameter,
    Resource,
    Risk,
    SchemaField,
    SourceRef,
    SpecValidation,
    SpecValidationIssue,
    StatusCode,
    Target,
    TechLeadQuestion,
    TracedItem,
)
from .enums import (
    ApiRuleEnforcement,
    ApiStyle,
    AuthBasis,
    AuthEffect,
    AuthScheme,
    AuthScope,
    EndpointKind,
    PaginationStyle,
    ParameterLocation,
    ResourceExposure,
    ResponseKind,
    SchemaKind,
    SpecFormat,
    VersioningStrategy,
)

__all__ = [
    "OPENAPI_VERSION",
    "SCHEMA_VERSION",
    "ApiAnalysis",
    "ApiArtifact",
    "ApiMetrics",
    "ApiRuleEnforcement",
    "ApiRuleMapping",
    "ApiSchema",
    "ApiStyle",
    "Audience",
    "AuthBasis",
    "AuthConfig",
    "AuthEffect",
    "AuthScheme",
    "AuthScope",
    "AuthorizationRule",
    "Conventions",
    "Coverage",
    "Endpoint",
    "EndpointKind",
    "ErrorEntry",
    "HttpMethod",
    "LogicalType",
    "OpenApiDocument",
    "Origin",
    "PaginationConfig",
    "PaginationStyle",
    "Parameter",
    "ParameterLocation",
    "QuestionStatus",
    "Resource",
    "ResourceExposure",
    "ResponseKind",
    "Risk",
    "RiskSeverity",
    "SchemaField",
    "SchemaKind",
    "SourceRef",
    "SpecFormat",
    "SpecValidation",
    "SpecValidationIssue",
    "StatusCode",
    "Target",
    "TechLeadQuestion",
    "TracedItem",
    "VersioningStrategy",
]
