"""Contrato de datos del Agente Arquitectura (ArchitectureArtifact v1.0.0)."""

from ai.agents.ef.schemas.enums import Audience, Origin, QuestionStatus

from .artifact import (
    SCHEMA_VERSION,
    Adr,
    ArchitectQuestion,
    ArchitectureAnalysis,
    ArchitectureArtifact,
    ArchitectureContext,
    ArchitectureMetrics,
    BoundedContext,
    Component,
    ComponentSourceRefs,
    Contract,
    Coverage,
    CrossCutting,
    Diagram,
    Diagrams,
    Integration,
    Risk,
    ScopeProfile,
    SourceRef,
    StackChoice,
    StyleDecision,
    TracedItem,
)
from .enums import (
    AdrStatus,
    ArchitectureStyle,
    ComponentType,
    ContractKind,
    CrossCuttingConcern,
    DiagramFormat,
    IntegrationDirection,
    IntegrationProtocol,
    RiskSeverity,
    SizeClass,
)

__all__ = [
    "SCHEMA_VERSION",
    "Adr",
    "AdrStatus",
    "ArchitectQuestion",
    "ArchitectureAnalysis",
    "ArchitectureArtifact",
    "ArchitectureContext",
    "ArchitectureMetrics",
    "ArchitectureStyle",
    "Audience",
    "BoundedContext",
    "Component",
    "ComponentSourceRefs",
    "ComponentType",
    "Contract",
    "ContractKind",
    "Coverage",
    "CrossCutting",
    "CrossCuttingConcern",
    "Diagram",
    "DiagramFormat",
    "Diagrams",
    "Integration",
    "IntegrationDirection",
    "IntegrationProtocol",
    "Origin",
    "QuestionStatus",
    "Risk",
    "RiskSeverity",
    "ScopeProfile",
    "SizeClass",
    "SourceRef",
    "StackChoice",
    "StyleDecision",
    "TracedItem",
]
