"""Tests del DDL, su validación, el diccionario y el diagrama ER (BD5).

La prueba de fuego de este bloque no es que el SQL "se vea bien", sino que
**se ejecuta**: `test_el_ddl_generado_crea_el_esquema_de_verdad` levanta una SQLite
en memoria, crea el esquema completo e inserta la semilla. Es la diferencia entre
un generador de texto y un generador de esquemas.
"""

import pytest

from ai.agents.arquitectura.schemas.examples import (
    example_artifact as arquitectura_example,
)
from ai.agents.bd.catalogs import run_catalogs
from ai.agents.bd.constraints import run_constraints
from ai.agents.bd.ddl.render import (
    build_ddl_scripts,
    render_create_table,
    render_default,
    render_seed_rows,
    render_type,
    topological_order,
)
from ai.agents.bd.ddl.smoke import run_ddl_on_sqlite
from ai.agents.bd.ddl.validate import check_structure, check_syntax, validate_ddl
from ai.agents.bd.dictionary import build_data_dictionary
from ai.agents.bd.er_diagram import build_er_diagram
from ai.agents.bd.indexes import run_indexes
from ai.agents.bd.load_sources import extract_sources
from ai.agents.bd.model_map import build_model_map
from ai.agents.bd.relations import run_relations
from ai.agents.bd.schemas.artifact import DdlScript, DictionaryEntry
from ai.agents.bd.tables import run_tables
from ai.agents.ef.schemas.examples import example_artifact as ef_example
from ai.orchestrator import build_bd_graph
from ai.orchestrator.checkpointer import build_memory_checkpointer
from tests.mocks import BdMapLLM

ENGINE = "postgresql"


def _sources():
    return extract_sources(
        ef_example().model_dump(mode="json"),
        arquitectura_example().model_dump(mode="json"),
        None,
    )


async def _modelo_completo(engine: str = ENGINE):
    """Modelo tras BD3 + BD4: la entrada real de DDL_GEN."""
    sources = _sources()
    mapa = build_model_map(sources, engine)
    tables, _, _, _ = await run_tables(BdMapLLM(), mapa, sources, engine)
    tables, _, _, _ = await run_relations(BdMapLLM(), tables, mapa, sources, engine)
    tables, _, _, _, _ = await run_constraints(BdMapLLM(), tables, sources, engine)
    tables, _, _, _ = await run_indexes(BdMapLLM(), tables, sources, engine)
    tables, seeds, _, _, _ = await run_catalogs(BdMapLLM(), tables, sources, engine)
    for table in tables:
        for column in table["columns"]:
            column["type"] = render_type(column, engine)
    return tables, seeds, sources


# --- Traducción de tipos (DB2) ----------------------------------------------


@pytest.mark.parametrize(
    "logical,extra,esperado",
    [
        ("string", {"length": 30}, "VARCHAR(30)"),
        ("text", {}, "TEXT"),
        ("bigint", {}, "BIGINT"),
        ("decimal", {"precision": 10, "scale": 3}, "NUMERIC(10,3)"),
        ("boolean", {}, "BOOLEAN"),
        ("date", {}, "DATE"),
        ("timestamp", {}, "TIMESTAMP"),
        ("uuid", {}, "UUID"),
        ("json", {}, "JSONB"),
    ],
)
def test_tipos_logicos_se_traducen_a_postgresql(logical, extra, esperado):
    """PostgreSQL 16 es el motor validado de la casa: su traducción es la crítica."""
    assert render_type({"logical_type": logical, **extra}, "postgresql") == esperado


def test_el_mismo_modelo_cambia_de_dialecto_sin_volver_a_llamar_al_LLM():
    """La portabilidad de DB2: el tipo lógico es neutro y el render, por motor."""
    columna = {"logical_type": "string", "length": 50}
    assert render_type(columna, "postgresql") == "VARCHAR(50)"
    assert render_type(columna, "sqlserver") == "NVARCHAR(50)"
    assert render_type(columna, "oracle") == "VARCHAR2(50)"
    assert render_type(columna, "mysql") == "VARCHAR(50)"


def test_boolean_default_se_adapta_al_motor():
    """`TRUE` solo existe en PostgreSQL; en los demás el booleano es numérico."""
    columna = {"logical_type": "boolean", "default": "true"}
    assert render_default(columna, "postgresql") == "TRUE"
    assert render_default(columna, "sqlserver") == "1"
    assert render_default(columna, "mysql") == "1"
    assert render_default({"logical_type": "integer", "default": None}, ENGINE) is None


# --- Render del DDL ---------------------------------------------------------


async def test_create_table_lleva_columnas_pk_unique_y_check():
    tables, _, _ = await _modelo_completo()
    siniestros = next(t for t in tables if t["name"] == "siniestros")
    sql = render_create_table(siniestros, ENGINE)

    assert sql.startswith("CREATE TABLE public.siniestros (")
    assert "siniestro_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL" in sql
    assert "CONSTRAINT pk_siniestros PRIMARY KEY (siniestro_id)" in sql
    # Las FK NO van aquí: viven en su propio script.
    assert "FOREIGN KEY" not in sql


async def test_las_fk_van_en_un_script_aparte():
    """Así el orden de creación deja de importar y un ciclo no rompe el esquema."""
    tables, seeds, _ = await _modelo_completo()
    scripts, _ = build_ddl_scripts(tables, seeds, ENGINE)
    por_tipo = {s["kind"]: s for s in scripts}

    assert "constraints" in por_tipo
    assert all(
        s.startswith("ALTER TABLE") and "FOREIGN KEY" in s
        for s in por_tipo["constraints"]["statements"]
    )
    assert por_tipo["constraints"]["order"] > por_tipo["tables"]["order"]


async def test_los_scripts_salen_ordenados_y_completos():
    tables, seeds, _ = await _modelo_completo()
    scripts, _ = build_ddl_scripts(tables, seeds, ENGINE)

    tipos = [s["kind"] for s in scripts]
    assert tipos[0] == "schema"  # PostgreSQL sí usa esquema
    assert "tables" in tipos and "indexes" in tipos and "seed" in tipos
    assert tipos[-1] == "rollback"
    assert [s["order"] for s in scripts] == sorted(s["order"] for s in scripts)

    for script in scripts:
        DdlScript.model_validate(script)
        assert script["engine"] == ENGINE
        # El texto completo termina cada sentencia con `;`.
        assert script["sql"].count(";") >= len(script["statements"])


async def test_el_rollback_es_destructivo_y_lo_avisa():
    tables, seeds, _ = await _modelo_completo()
    scripts, _ = build_ddl_scripts(tables, seeds, ENGINE)
    rollback = next(s for s in scripts if s["kind"] == "rollback")

    assert "DESTRUCTIVO" in rollback["sql"]
    assert all(s.startswith("DROP TABLE IF EXISTS") for s in rollback["statements"])
    # En orden inverso al de creación: los hijos primero.
    tablas_script = next(s for s in scripts if s["kind"] == "tables")
    creadas = [
        s.split("CREATE TABLE ")[1].split(" (")[0] for s in tablas_script["statements"]
    ]
    borradas = [s.split("IF EXISTS ")[1] for s in rollback["statements"]]
    assert borradas == list(reversed(creadas))


async def test_la_semilla_se_renderiza_con_literales_bien_escapados():
    tables, seeds, _ = await _modelo_completo()
    scripts, _ = build_ddl_scripts(tables, seeds, ENGINE)
    semilla = next(s for s in scripts if s["kind"] == "seed")
    assert semilla["statements"]
    assert all(s.startswith("INSERT INTO") for s in semilla["statements"])


def test_las_comillas_simples_del_dominio_se_escapan():
    """Un valor con apóstrofo no puede romper el INSERT."""
    table = {
        "name": "motivos",
        "schema_name": "public",
        "columns": [
            {"name": "nombre", "logical_type": "string", "length": 50},
        ],
    }
    seed = {"columns": ["nombre"], "rows": [{"nombre": "Robo d'almacén"}]}
    sql = render_seed_rows(seed, table, ENGINE)[0]
    assert "'Robo d''almacén'" in sql


def test_orden_topologico_pone_los_padres_primero():
    tables = [
        {"name": "siniestros", "foreign_keys": [{"references_table": "guias"}]},
        {"name": "guias", "foreign_keys": []},
    ]
    ordenadas, ciclos = topological_order(tables)
    assert [t["name"] for t in ordenadas] == ["guias", "siniestros"]
    assert ciclos == []


def test_un_ciclo_de_fk_no_pierde_tablas_y_se_reporta():
    tables = [
        {"name": "a", "foreign_keys": [{"references_table": "b"}]},
        {"name": "b", "foreign_keys": [{"references_table": "a"}]},
    ]
    ordenadas, ciclos = topological_order(tables)
    assert {t["name"] for t in ordenadas} == {"a", "b"}
    assert set(ciclos) == {"a", "b"}


def test_una_autoreferencia_no_es_un_ciclo():
    """Una tabla que se referencia a sí misma (jerarquía) se crea sin problema."""
    tables = [{"name": "areas", "foreign_keys": [{"references_table": "areas"}]}]
    ordenadas, ciclos = topological_order(tables)
    assert [t["name"] for t in ordenadas] == ["areas"]
    assert ciclos == []


# --- Validación L1 (estructural) --------------------------------------------


def _tabla(nombre, columnas, **extra):
    base = {
        "id": f"TBL-{nombre}",
        "name": nombre,
        "columns": [
            {"id": f"COL-{nombre}-{c['name']}", "nullable": True, **c} for c in columnas
        ],
        "primary_key": {"name": f"pk_{nombre}", "columns": [columnas[0]["name"]]},
        "foreign_keys": [],
        "unique_constraints": [],
        "check_constraints": [],
        "indexes": [],
    }
    base.update(extra)
    base["columns"][0]["nullable"] = False
    return base


def test_l1_detecta_fk_a_tabla_inexistente():
    tabla = _tabla("siniestros", [{"name": "id", "logical_type": "bigint"}])
    tabla["foreign_keys"] = [
        {
            "id": "FK-001",
            "name": "fk_x",
            "columns": ["id"],
            "references_table": "no_existe",
            "references_columns": ["id"],
        }
    ]
    resultado = check_structure([tabla], [], ENGINE)
    assert any(e["code"] == "fk_target_missing" for e in resultado["errors"])
    assert resultado["checks"]["all_fks_resolve"] is False


def test_l1_detecta_fk_a_columna_inexistente_y_tipo_incompatible():
    padre = _tabla("guias", [{"name": "guia_id", "logical_type": "bigint"}])
    hijo = _tabla(
        "siniestros",
        [
            {"name": "siniestro_id", "logical_type": "bigint"},
            {"name": "guia_id", "logical_type": "string", "length": 10},
        ],
    )
    hijo["foreign_keys"] = [
        {
            "id": "FK-001",
            "name": "fk_a",
            "columns": ["guia_id"],
            "references_table": "guias",
            "references_columns": ["guia_id"],
        },
        {
            "id": "FK-002",
            "name": "fk_b",
            "columns": ["guia_id"],
            "references_table": "guias",
            "references_columns": ["fantasma"],
        },
    ]
    errores = {e["code"] for e in check_structure([padre, hijo], [], ENGINE)["errors"]}
    assert "fk_type_mismatch" in errores
    assert "fk_target_column_missing" in errores


def test_l1_exige_clave_primaria():
    tabla = _tabla("sin_pk", [{"name": "x", "logical_type": "integer"}])
    tabla["primary_key"] = None
    resultado = check_structure([tabla], [], ENGINE)
    assert any(e["code"] == "table_without_pk" for e in resultado["errors"])
    assert resultado["checks"]["all_tables_have_pk"] is False


def test_l1_detecta_columnas_y_tablas_duplicadas():
    tabla = _tabla(
        "guias",
        [
            {"name": "guia_id", "logical_type": "bigint"},
            {"name": "GUIA_ID", "logical_type": "bigint"},
        ],
    )
    errores = {e["code"] for e in check_structure([tabla, tabla], [], ENGINE)["errors"]}
    assert "duplicate_column_name" in errores
    assert "duplicate_table_name" in errores


def test_l1_detecta_identificador_demasiado_largo_para_oracle():
    tabla = _tabla("guias", [{"name": "guia_id", "logical_type": "bigint"}])
    tabla["primary_key"]["name"] = "pk_" + "x" * 40
    resultado = check_structure([tabla], [], "oracle")
    assert any(e["code"] == "identifier_too_long" for e in resultado["errors"])
    # En PostgreSQL (63) el mismo nombre cabe.
    assert not any(
        e["code"] == "identifier_too_long"
        for e in check_structure([tabla], [], "postgresql")["errors"]
    )


def test_l1_detecta_nombres_de_constraint_repetidos():
    a = _tabla("guias", [{"name": "guia_id", "logical_type": "bigint"}])
    b = _tabla("siniestros", [{"name": "siniestro_id", "logical_type": "bigint"}])
    b["primary_key"]["name"] = a["primary_key"]["name"]
    errores = {e["code"] for e in check_structure([a, b], [], ENGINE)["errors"]}
    assert "duplicate_constraint_name" in errores


def test_l1_detecta_pk_que_admite_nulos():
    tabla = _tabla("guias", [{"name": "guia_id", "logical_type": "bigint"}])
    tabla["columns"][0]["nullable"] = True
    errores = {e["code"] for e in check_structure([tabla], [], ENGINE)["errors"]}
    assert "nullable_pk_column" in errores


def test_l1_detecta_set_null_sobre_columna_obligatoria():
    padre = _tabla("guias", [{"name": "guia_id", "logical_type": "bigint"}])
    hijo = _tabla(
        "siniestros",
        [
            {"name": "siniestro_id", "logical_type": "bigint"},
            {"name": "guia_id", "logical_type": "bigint", "nullable": False},
        ],
    )
    hijo["foreign_keys"] = [
        {
            "id": "FK-001",
            "name": "fk_a",
            "columns": ["guia_id"],
            "references_table": "guias",
            "references_columns": ["guia_id"],
            "on_delete": "set_null",
        }
    ]
    errores = {e["code"] for e in check_structure([padre, hijo], [], ENGINE)["errors"]}
    assert "fk_set_null_on_not_null" in errores


def test_l1_valida_la_semilla_contra_su_tabla():
    tabla = _tabla(
        "estados",
        [
            {"name": "estado_id", "logical_type": "bigint", "is_generated": True},
            {"name": "codigo", "logical_type": "string", "nullable": False},
        ],
    )
    resultado = check_structure(
        [tabla],
        [
            {
                "id": "SEED-001",
                "table": "estados",
                "columns": ["codigo"],
                "rows": [{"codigo": None}],
            },
            {"id": "SEED-002", "table": "fantasma", "columns": ["x"], "rows": []},
            {
                "id": "SEED-003",
                "table": "estados",
                "columns": ["inventada"],
                "rows": [],
            },
        ],
        ENGINE,
    )
    errores = {e["code"] for e in resultado["errors"]}
    assert "seed_missing_required" in errores
    assert "seed_table_missing" in errores
    assert "seed_unknown_column" in errores
    assert resultado["checks"]["seed_respects_constraints"] is False


def test_l1_distingue_omitir_una_columna_con_default_de_pasarle_NULL():
    """Un NULL explícito NO activa el DEFAULT: la inserción falla igualmente.

    Regresión: el catálogo listaba TODAS sus columnas en el INSERT, así que
    `activo` (NOT NULL DEFAULT true) recibía NULL y la creación del esquema
    fallaba. Lo detectó la ejecución real (L3a), no la validación estática.
    """
    tabla = _tabla(
        "estados",
        [
            {"name": "estado_id", "logical_type": "bigint", "is_generated": True},
            {"name": "codigo", "logical_type": "string", "nullable": False},
            {
                "name": "activo",
                "logical_type": "boolean",
                "nullable": False,
                "default": "true",
            },
        ],
    )
    # Omitir `activo` es correcto: el motor aplica su DEFAULT.
    omitida = check_structure(
        [tabla],
        [
            {
                "id": "S1",
                "table": "estados",
                "columns": ["codigo"],
                "rows": [{"codigo": "A"}],
            }
        ],
        ENGINE,
    )
    assert omitida["errors"] == []

    # Listarla con NULL, no: el DEFAULT no se aplica.
    con_nulo = check_structure(
        [tabla],
        [
            {
                "id": "S2",
                "table": "estados",
                "columns": ["codigo", "activo"],
                "rows": [{"codigo": "A", "activo": None}],
            }
        ],
        ENGINE,
    )
    assert any(e["code"] == "seed_missing_required" for e in con_nulo["errors"])


async def test_la_semilla_solo_lista_las_columnas_que_trae():
    """El INSERT no menciona columnas que la fila no aporta (dejarlas al DEFAULT)."""
    tables, seeds, _ = await _modelo_completo()
    assert seeds
    for seed in seeds:
        tabla = next(t for t in tables if t["name"] == seed["table"])
        columnas = {c["name"] for c in tabla["columns"]}
        assert set(seed["columns"]) <= columnas
        for row in seed["rows"]:
            assert set(seed["columns"]) == set(
                row
            ), "cada fila debe traer exactamente las columnas declaradas"


def test_l1_avisa_de_palabras_reservadas_sin_bloquear():
    tabla = _tabla(
        "guias",
        [
            {"name": "guia_id", "logical_type": "bigint"},
            {"name": "order", "logical_type": "integer"},
        ],
    )
    resultado = check_structure([tabla], [], ENGINE)
    assert any(w["code"] == "reserved_word" for w in resultado["warnings"])
    assert not any(e["code"] == "reserved_word" for e in resultado["errors"])


# --- Validación L2 (sqlglot en el dialecto destino) -------------------------


async def test_l2_parsea_todo_el_ddl_generado_en_postgres():
    """Si el SQL generado no parsea, el bug está en el renderizador."""
    tables, seeds, _ = await _modelo_completo()
    scripts, _ = build_ddl_scripts(tables, seeds, ENGINE)
    resultado = check_syntax(scripts, ENGINE)
    assert resultado["errors"] == [], resultado["errors"]
    assert resultado["checks"]["syntax_parses"] is True


@pytest.mark.parametrize("engine", ["postgresql", "sqlserver", "oracle", "mysql"])
async def test_l2_parsea_en_los_cuatro_dialectos(engine: str):
    tables, seeds, _ = await _modelo_completo(engine)
    scripts, _ = build_ddl_scripts(tables, seeds, engine)
    assert check_syntax(scripts, engine)["errors"] == []


def test_l2_detecta_sql_invalido():
    scripts = [
        {
            "id": "DDL-001",
            "name": "roto.sql",
            "order": 1,
            "kind": "tables",
            "statements": ["CREATE TABLE ("],
        }
    ]
    resultado = check_syntax(scripts, ENGINE)
    assert any(e["code"] == "sql_syntax_error" for e in resultado["errors"])


async def test_validate_ddl_compone_el_bloque_del_artefacto():
    tables, seeds, _ = await _modelo_completo()
    scripts, ciclos = build_ddl_scripts(tables, seeds, ENGINE)
    validation = validate_ddl(tables, seeds, scripts, ENGINE, cycles=ciclos)

    assert validation["syntax_ok"] is True
    assert validation["errors"] == []
    assert validation["engine"] == ENGINE
    assert validation["validator"] == "estructural+sqlglot"
    # Parseado no es ejecutado: el artefacto no presume de lo que no hizo.
    assert validation["executed"] is False
    assert all(validation["checks"].values())


def test_un_ciclo_es_aviso_y_no_error():
    """El esquema se crea igual; el problema es insertar la primera fila."""
    validation = validate_ddl([], [], [], ENGINE, cycles=["a", "b"])
    assert validation["checks"]["topological_order_ok"] is False
    assert any(w["code"] == "fk_cycle" for w in validation["warnings"])
    assert not any(e["code"] == "fk_cycle" for e in validation["errors"])


# --- Validación L3a: EJECUCIÓN real contra SQLite ---------------------------


async def test_el_ddl_generado_crea_el_esquema_de_verdad():
    """La prueba de fuego: el DDL se ejecuta y el esquema queda creado.

    Es un smoke test (SQLite usa afinidades de tipo), pero caza lo que ninguna
    validación estática puede: que las sentencias se apliquen en un motor real, en
    orden, y que la semilla no viole sus propias restricciones.
    """
    tables, seeds, _ = await _modelo_completo()

    resultado = run_ddl_on_sqlite(tables, seeds, ENGINE)
    assert resultado.ok, f"falló «{resultado.failed_statement}»: {resultado.error}"
    assert resultado.executed >= len(tables)
    # Todas las tablas del modelo existen en la base efímera.
    assert {t["name"] for t in tables} <= resultado.tables


async def test_la_semilla_se_inserta_sin_violar_restricciones():
    tables, seeds, _ = await _modelo_completo()
    scripts, _ = build_ddl_scripts(tables, seeds, ENGINE)
    semilla = next((s for s in scripts if s["kind"] == "seed"), None)
    assert semilla is not None and semilla["statements"]

    resultado = run_ddl_on_sqlite(tables, seeds, ENGINE)
    assert resultado.ok


async def test_una_fk_rota_hace_fallar_la_ejecucion():
    """Control negativo: si el smoke test no detectara esto, no probaría nada."""
    tables, seeds, _ = await _modelo_completo()
    for table in tables:
        for fk in table["foreign_keys"]:
            fk["references_table"] = "tabla_inexistente"
    resultado = run_ddl_on_sqlite(tables, seeds, ENGINE)
    assert not resultado.ok
    assert "no existe" in resultado.error


# --- Diccionario de datos ---------------------------------------------------


async def test_el_diccionario_cubre_todas_las_columnas():
    tables, _, _ = await _modelo_completo()
    entradas = build_data_dictionary(tables, ENGINE)

    reales = {(t["name"], c["name"]) for t in tables for c in t["columns"]}
    assert {(e["table"], e["column"]) for e in entradas} == reales
    for entrada in entradas:
        DictionaryEntry.model_validate(entrada)
        assert entrada["type"]
        assert entrada["id"].startswith("DIC-")


async def test_el_diccionario_marca_el_papel_en_las_claves():
    tables, _, _ = await _modelo_completo()
    entradas = {
        (e["table"], e["column"]): e for e in build_data_dictionary(tables, ENGINE)
    }
    assert entradas[("siniestros", "siniestro_id")]["key"] == "PK"
    assert "FK" in entradas[("siniestros", "guia_id")]["key"]
    assert entradas[("siniestros", "fecha_siniestro")]["key"] == "—"


async def test_el_diccionario_hereda_descripciones_de_TABLES():
    """No hay segunda pasada al LLM: el diccionario es una proyección del modelo."""
    tables, _, _ = await _modelo_completo()
    entradas = build_data_dictionary(tables, ENGINE)
    con_descripcion = [e for e in entradas if e["description"]]
    assert con_descripcion
    for entrada in con_descripcion:
        columna = next(
            c
            for t in tables
            if t["name"] == entrada["table"]
            for c in t["columns"]
            if c["name"] == entrada["column"]
        )
        assert entrada["description"] == columna["description"]


# --- Diagrama ER ------------------------------------------------------------


async def test_el_diagrama_es_mermaid_valido_por_construccion():
    tables, _, _ = await _modelo_completo()
    diagrama = build_er_diagram(tables)

    assert diagrama["format"] == "mermaid"
    lineas = diagrama["code"].splitlines()
    assert lineas[0] == "erDiagram"
    # Cada tabla tiene su bloque de atributos y cada bloque, su cierre.
    assert lineas.count("  }") == len(tables)
    for table in tables:
        assert f"  {table['name']} {{" in lineas


async def test_el_diagrama_dibuja_las_relaciones_con_su_cardinalidad():
    tables, _, _ = await _modelo_completo()
    code = build_er_diagram(tables)["code"]
    # REL-001 es 1:N con FK obligatoria: uno-a-muchos con lado izquierdo fuerte.
    assert 'guias ||--o{ siniestros : "REL-001"' in code


def test_una_fk_unica_se_dibuja_como_uno_a_uno():
    tables = [
        {
            "name": "guias",
            "columns": [
                {"name": "guia_id", "logical_type": "bigint", "is_primary_key": True}
            ],
            "foreign_keys": [],
            "unique_constraints": [],
        },
        {
            "name": "detalles",
            "columns": [
                {
                    "name": "detalle_id",
                    "logical_type": "bigint",
                    "is_primary_key": True,
                },
                {"name": "guia_id", "logical_type": "bigint", "nullable": False},
            ],
            "foreign_keys": [
                {
                    "name": "fk_d_g",
                    "columns": ["guia_id"],
                    "references_table": "guias",
                    "references_columns": ["guia_id"],
                    "relationship_ref": "REL-009",
                }
            ],
            "unique_constraints": [{"name": "uq_d_g", "columns": ["guia_id"]}],
        },
    ]
    code = build_er_diagram(tables)["code"]
    assert 'guias ||--|| detalles : "REL-009"' in code


def test_una_fk_opcional_se_dibuja_como_padre_opcional():
    tables = [
        {
            "name": "estados",
            "columns": [
                {"name": "estado_id", "logical_type": "bigint", "is_primary_key": True}
            ],
            "foreign_keys": [],
            "unique_constraints": [],
        },
        {
            "name": "siniestros",
            "columns": [
                {
                    "name": "siniestro_id",
                    "logical_type": "bigint",
                    "is_primary_key": True,
                },
                {"name": "estado_id", "logical_type": "bigint", "nullable": True},
            ],
            "foreign_keys": [
                {
                    "name": "fk_s_e",
                    "columns": ["estado_id"],
                    "references_table": "estados",
                    "references_columns": ["estado_id"],
                    "relationship_ref": None,
                }
            ],
            "unique_constraints": [],
        },
    ]
    code = build_er_diagram(tables)["code"]
    assert "estados |o--o{ siniestros" in code


def test_los_tipos_del_diagrama_son_un_solo_token():
    """`NUMERIC(12,2)` rompería el parseo de atributos de Mermaid."""
    tables = [
        {
            "name": "siniestros",
            "columns": [
                {
                    "name": "monto",
                    "logical_type": "decimal",
                    "type": "NUMERIC(12,2)",
                    "is_primary_key": False,
                }
            ],
            "foreign_keys": [],
            "unique_constraints": [],
        }
    ]
    code = build_er_diagram(tables)["code"]
    assert "    decimal monto" in code
    assert "NUMERIC" not in code


# --- Integración en el grafo ------------------------------------------------


async def _noop_persist(job_id, artifact, status, metrics):
    return None


async def test_grafo_completo_hasta_BD5():
    graph = build_bd_graph(build_memory_checkpointer())
    state = {
        "job_id": "BD-5",
        "architecture_job_id": "AR-1",
        "architecture_artifact": arquitectura_example().model_dump(mode="json"),
        "architecture_artifact_hash": "ar123",
        "architecture_ready": True,
        "ef_job_id": "EF-1",
        "ef_artifact": ef_example().model_dump(mode="json"),
        "ef_artifact_hash": "ef123",
        # El motor validado de la casa, por encima del ejemplo de arquitectura.
        "engine_override": "postgresql",
    }
    config = {
        "configurable": {
            "thread_id": "BD-5",
            "llm": BdMapLLM(),
            "persist": _noop_persist,
        }
    }
    result = await graph.ainvoke(state, config)
    art = result["artifact"]

    assert art["target"]["engine"] == "postgresql"
    assert art["target"]["engine_version"] == "16"

    # El DDL existe, es válido y el semáforo del DDL se pone en verde.
    assert art["ddl_scripts"]
    assert art["validation"]["syntax_ok"] is True
    assert art["validation"]["errors"] == []
    assert art["metrics"]["ddl_valid"] is True

    # Cada columna lleva ya su tipo físico renderizado.
    assert all(c["type"] for t in art["tables"] for c in t["columns"])

    assert art["data_dictionary"]
    assert art["er_diagram"]["code"].startswith("erDiagram")
    assert result["status"] == "COMPLETED"


async def test_el_ddl_del_grafo_se_ejecuta():
    """De punta a punta: lo que el pipeline entrega crea un esquema real."""
    graph = build_bd_graph(build_memory_checkpointer())
    result = await graph.ainvoke(
        {
            "job_id": "BD-6",
            "architecture_job_id": "AR-1",
            "architecture_artifact": arquitectura_example().model_dump(mode="json"),
            "architecture_artifact_hash": "ar123",
            "architecture_ready": True,
            "ef_job_id": "EF-1",
            "ef_artifact": ef_example().model_dump(mode="json"),
            "ef_artifact_hash": "ef123",
            "engine_override": "postgresql",
        },
        {
            "configurable": {
                "thread_id": "BD-6",
                "llm": BdMapLLM(),
                "persist": _noop_persist,
            }
        },
    )
    art = result["artifact"]
    resultado = run_ddl_on_sqlite(art["tables"], art["seed_data"], "postgresql")
    assert resultado.ok, f"falló «{resultado.failed_statement}»: {resultado.error}"
