"""Contrato de datos del Agente BD (DatabaseArtifact v1.0.0)."""

from ai.agents.arquitectura.schemas.enums import RiskSeverity
from ai.agents.ef.schemas.enums import Audience, Origin, QuestionStatus

from .artifact import (
    SCHEMA_VERSION,
    CheckConstraint,
    Column,
    Conventions,
    Coverage,
    DatabaseAnalysis,
    DatabaseArtifact,
    DatabaseMetrics,
    DbaQuestion,
    DdlScript,
    DdlValidation,
    DesignDecision,
    DictionaryEntry,
    ErDiagram,
    ForeignKey,
    Index,
    Normalization,
    PrimaryKey,
    Risk,
    RuleMapping,
    SeedData,
    SourceRef,
    Table,
    Target,
    TracedItem,
    UniqueConstraint,
    ValidationIssue,
)
from .enums import (
    DbEngine,
    DdlScriptKind,
    DecisionScope,
    DiagramFormat,
    LogicalType,
    NormalizationForm,
    PrimaryKeyStrategy,
    ReferentialAction,
    RuleEnforcement,
    TableKind,
    VolumeEstimate,
)

__all__ = [
    "SCHEMA_VERSION",
    "Audience",
    "CheckConstraint",
    "Column",
    "Conventions",
    "Coverage",
    "DatabaseAnalysis",
    "DatabaseArtifact",
    "DatabaseMetrics",
    "DbEngine",
    "DbaQuestion",
    "DdlScript",
    "DdlScriptKind",
    "DdlValidation",
    "DecisionScope",
    "DesignDecision",
    "DiagramFormat",
    "DictionaryEntry",
    "ErDiagram",
    "ForeignKey",
    "Index",
    "LogicalType",
    "Normalization",
    "NormalizationForm",
    "Origin",
    "PrimaryKey",
    "PrimaryKeyStrategy",
    "QuestionStatus",
    "ReferentialAction",
    "Risk",
    "RiskSeverity",
    "RuleEnforcement",
    "RuleMapping",
    "SeedData",
    "SourceRef",
    "Table",
    "TableKind",
    "Target",
    "TracedItem",
    "UniqueConstraint",
    "ValidationIssue",
    "VolumeEstimate",
]
