"""Ejemplo válido de DatabaseArtifact (dominio: siniestros logísticos).

Deriva del mismo EF de ejemplo que Scrum y Arquitectura (ENT-001 Siniestro,
ENT-002 Guia, REL-001, BR-001, VAL-001, FLD-001/002, API-001, CRUD-001), de modo
que sirva de fixture en los tests de los bloques posteriores: el modelo físico de
abajo es exactamente lo que el pipeline debería producir a partir de ese EF.

Incluye a propósito los tres casos que el contrato debe saber representar:
una tabla de entidad, un catálogo con semilla citada y una regla del EF que **no**
es expresable como constraint declarativa (queda en ``rule_mappings`` como
``application``, nunca descartada en silencio).
"""

from ai.agents.arquitectura.schemas.enums import RiskSeverity
from ai.agents.ef.schemas.artifact import Observation, TokenMetrics
from ai.agents.ef.schemas.enums import Audience, Origin

from .artifact import (
    CheckConstraint,
    Column,
    Conventions,
    Coverage,
    DatabaseAnalysis,
    DatabaseArtifact,
    DatabaseMetrics,
    DbaQuestion,
    DdlScript,
    DdlValidation,
    DesignDecision,
    DictionaryEntry,
    ErDiagram,
    ForeignKey,
    Index,
    Normalization,
    PrimaryKey,
    Risk,
    RuleMapping,
    SeedData,
    SourceRef,
    Table,
    Target,
    UniqueConstraint,
)
from .enums import (
    DbEngine,
    DdlScriptKind,
    DecisionScope,
    LogicalType,
    PrimaryKeyStrategy,
    ReferentialAction,
    RuleEnforcement,
    TableKind,
    VolumeEstimate,
)

_DDL_GUIAS = (
    "CREATE TABLE public.guias (\n"
    "  guia_id BIGINT GENERATED BY DEFAULT AS IDENTITY,\n"
    "  numero VARCHAR(30) NOT NULL,\n"
    "  CONSTRAINT pk_guias PRIMARY KEY (guia_id),\n"
    "  CONSTRAINT uq_guias_numero UNIQUE (numero)\n"
    ")"
)

_DDL_SINIESTROS = (
    "CREATE TABLE public.siniestros (\n"
    "  siniestro_id BIGINT GENERATED BY DEFAULT AS IDENTITY,\n"
    "  guia_id BIGINT NOT NULL,\n"
    "  fecha_siniestro DATE NOT NULL,\n"
    "  monto NUMERIC(12,2),\n"
    "  estado_id BIGINT NOT NULL,\n"
    "  CONSTRAINT pk_siniestros PRIMARY KEY (siniestro_id),\n"
    "  CONSTRAINT ck_siniestros_monto_no_negativo CHECK (monto >= 0)\n"
    ")"
)


def _tabla_guias() -> Table:
    """Tabla de entidad con clave natural preservada como UNIQUE."""
    return Table(
        id="TBL-001",
        name="guias",
        schema_name="public",
        entity_ref="ENT-002",
        kind=TableKind.ENTITY,
        description="Documento de envío asociado al siniestro.",
        columns=[
            Column(
                id="COL-0001",
                name="guia_id",
                ordinal=1,
                logical_type=LogicalType.BIGINT,
                type="BIGINT GENERATED BY DEFAULT AS IDENTITY",
                nullable=False,
                is_primary_key=True,
                is_generated=True,
                description="Identificador interno de la guía.",
                example="8801",
                source_refs=["ENT-002"],
                confidence=0.9,
                origin=Origin.DERIVED,
            ),
            Column(
                id="COL-0002",
                name="numero",
                ordinal=2,
                logical_type=LogicalType.STRING,
                type="VARCHAR(30)",
                length=30,
                nullable=False,
                description="Número de guía impreso en el documento de envío.",
                example="URB-000123",
                field_ref="FLD-001",
                source_refs=["ENT-002", "FLD-001"],
                confidence=0.9,
                origin=Origin.STATED,
            ),
        ],
        primary_key=PrimaryKey(
            name="pk_guias",
            columns=["guia_id"],
            strategy=PrimaryKeyStrategy.SURROGATE,
            rationale=(
                "El número de guía es clave natural del negocio, pero puede "
                "cambiar de formato: se conserva como UNIQUE y la PK es subrogada."
            ),
            origin=Origin.DERIVED,
        ),
        unique_constraints=[
            UniqueConstraint(
                id="UQ-001",
                name="uq_guias_numero",
                columns=["numero"],
                description="El número de guía no se repite.",
                source_refs=["FLD-001"],
                confidence=0.85,
                origin=Origin.DERIVED,
            )
        ],
        estimated_volume=VolumeEstimate.ALTA,
        normalization=Normalization(),
        source_refs=["ENT-002"],
        confidence=0.8,
        origin=Origin.DERIVED,
    )


def _tabla_siniestros() -> Table:
    """Tabla transaccional: FK, CHECK de una regla del EF e índice justificado."""
    return Table(
        id="TBL-002",
        name="siniestros",
        schema_name="public",
        entity_ref="ENT-001",
        kind=TableKind.ENTITY,
        description="Evento logístico no asegurado reportado sobre una guía.",
        columns=[
            Column(
                id="COL-0003",
                name="siniestro_id",
                ordinal=1,
                logical_type=LogicalType.BIGINT,
                type="BIGINT GENERATED BY DEFAULT AS IDENTITY",
                nullable=False,
                is_primary_key=True,
                is_generated=True,
                description="Identificador interno del siniestro.",
                example="12345",
                source_refs=["ENT-001"],
                confidence=0.9,
                origin=Origin.DERIVED,
            ),
            Column(
                id="COL-0004",
                name="guia_id",
                ordinal=2,
                logical_type=LogicalType.BIGINT,
                type="BIGINT",
                nullable=False,
                description=(
                    "Guía sobre la que se reporta el siniestro. Obligatoria: "
                    "BR-001 impide registrar un siniestro sin guía."
                ),
                example="8801",
                source_refs=["REL-001", "BR-001"],
                confidence=0.85,
                origin=Origin.DERIVED,
            ),
            Column(
                id="COL-0005",
                name="fecha_siniestro",
                ordinal=3,
                logical_type=LogicalType.DATE,
                type="DATE",
                nullable=False,
                description="Fecha en que ocurrió el siniestro.",
                example="2026-03-14",
                field_ref="FLD-002",
                source_refs=["ENT-001", "FLD-002"],
                confidence=0.9,
                origin=Origin.STATED,
            ),
            Column(
                id="COL-0006",
                name="monto",
                ordinal=4,
                logical_type=LogicalType.DECIMAL,
                type="NUMERIC(12,2)",
                precision=12,
                scale=2,
                nullable=True,
                description="Monto económico estimado del siniestro, en soles.",
                example="1250.50",
                source_refs=["ENT-001"],
                # El EF no precisa la escala: se aplicó el default y se preguntó.
                type_ambiguous=True,
                confidence=0.55,
                origin=Origin.DERIVED,
            ),
            Column(
                id="COL-0007",
                name="estado_id",
                ordinal=5,
                logical_type=LogicalType.BIGINT,
                type="BIGINT",
                nullable=False,
                description="Estado actual del siniestro (catálogo).",
                example="1",
                source_refs=["BR-001"],
                confidence=0.7,
                origin=Origin.DERIVED,
            ),
        ],
        primary_key=PrimaryKey(
            name="pk_siniestros",
            columns=["siniestro_id"],
            strategy=PrimaryKeyStrategy.SURROGATE,
            rationale="Sin clave natural en el EF: PK subrogada por identidad.",
            origin=Origin.DERIVED,
        ),
        foreign_keys=[
            ForeignKey(
                id="FK-001",
                name="fk_siniestros_guias",
                columns=["guia_id"],
                references_table="guias",
                references_columns=["guia_id"],
                on_delete=ReferentialAction.RESTRICT,
                on_update=ReferentialAction.NO_ACTION,
                relationship_ref="REL-001",
                rationale=(
                    "REL-001 es 1:N (una guía, varios siniestros): la FK vive en "
                    "el lado N. RESTRICT porque el EF no autoriza borrado en cascada."
                ),
                source_refs=["REL-001"],
                confidence=0.85,
                origin=Origin.DERIVED,
            ),
            ForeignKey(
                id="FK-002",
                name="fk_siniestros_siniestro_estados",
                columns=["estado_id"],
                references_table="siniestro_estados",
                references_columns=["estado_id"],
                on_delete=ReferentialAction.RESTRICT,
                relationship_ref=None,
                rationale="El estado del siniestro se normaliza como catálogo.",
                source_refs=["BR-001"],
                confidence=0.7,
                origin=Origin.DERIVED,
            ),
        ],
        check_constraints=[
            CheckConstraint(
                id="CK-001",
                name="ck_siniestros_monto_no_negativo",
                expression="monto >= 0",
                description="El monto del siniestro no puede ser negativo.",
                source_refs=["VAL-001"],
                confidence=0.7,
                origin=Origin.DERIVED,
            )
        ],
        indexes=[
            Index(
                id="IDX-001",
                name="ix_siniestros_estado_fecha",
                columns=["estado_id", "fecha_siniestro"],
                unique=False,
                rationale=(
                    "El listado de siniestros se consulta por estado y rango de "
                    "fechas (API-001 y la matriz CRUD-001)."
                ),
                access_pattern_refs=["API-001", "CRUD-001"],
                source_refs=["API-001"],
                confidence=0.7,
                origin=Origin.DERIVED,
            )
        ],
        estimated_volume=VolumeEstimate.ALTA,
        normalization=Normalization(),
        source_refs=["ENT-001", "MOD-001"],
        confidence=0.85,
        origin=Origin.STATED,
    )


def _tabla_estados() -> Table:
    """Catálogo detectado a partir del vocabulario de estados del EF."""
    return Table(
        id="TBL-003",
        name="siniestro_estados",
        schema_name="public",
        entity_ref=None,  # no es una entidad del EF: es un catálogo derivado
        kind=TableKind.CATALOG,
        description="Estados por los que pasa un siniestro.",
        columns=[
            Column(
                id="COL-0008",
                name="estado_id",
                ordinal=1,
                logical_type=LogicalType.BIGINT,
                type="BIGINT GENERATED BY DEFAULT AS IDENTITY",
                nullable=False,
                is_primary_key=True,
                is_generated=True,
                description="Identificador del estado.",
                example="1",
                source_refs=["PRO-001"],
                confidence=0.8,
                origin=Origin.DERIVED,
            ),
            Column(
                id="COL-0009",
                name="codigo",
                ordinal=2,
                logical_type=LogicalType.STRING,
                type="VARCHAR(30)",
                length=30,
                nullable=False,
                description="Código estable del estado.",
                example="REGISTRADO",
                source_refs=["PRO-001"],
                confidence=0.8,
                origin=Origin.DERIVED,
            ),
            Column(
                id="COL-0010",
                name="nombre",
                ordinal=3,
                logical_type=LogicalType.STRING,
                type="VARCHAR(100)",
                length=100,
                nullable=False,
                description="Nombre legible del estado.",
                example="Registrado",
                source_refs=["PRO-001"],
                confidence=0.8,
                origin=Origin.DERIVED,
            ),
        ],
        primary_key=PrimaryKey(
            name="pk_siniestro_estados",
            columns=["estado_id"],
            strategy=PrimaryKeyStrategy.SURROGATE,
            origin=Origin.DERIVED,
        ),
        unique_constraints=[
            UniqueConstraint(
                id="UQ-002",
                name="uq_siniestro_estados_codigo",
                columns=["codigo"],
                source_refs=["PRO-001"],
                confidence=0.8,
                origin=Origin.DERIVED,
            )
        ],
        estimated_volume=VolumeEstimate.BAJA,
        source_refs=["PRO-001"],
        confidence=0.7,
        origin=Origin.DERIVED,
    )


def example_artifact() -> DatabaseArtifact:
    """Construye un DatabaseArtifact v1.0.0 completo y válido."""
    return DatabaseArtifact(
        source=SourceRef(
            architecture_job_id="job-arq-001",
            architecture_artifact_hash="a" * 16,
            scrum_job_id="job-scrum-001",
            scrum_artifact_hash="b" * 16,
            ef_job_id="job-ef-001",
            ef_artifact_hash="c" * 16,
            ready_snapshot=True,
        ),
        target=Target(
            engine=DbEngine.POSTGRESQL,
            engine_version="16",
            engine_source_ref="STK-004",
            engine_decided=True,
            conventions=Conventions(
                naming_case="snake_case",
                table_number="plural",
                pk_strategy=PrimaryKeyStrategy.SURROGATE,
                audit_columns=False,
                soft_delete=False,
                schema_name="public",
            ),
            conventions_source="ai/knowledge/db_conventions.yaml@v0",
        ),
        tables=[_tabla_guias(), _tabla_siniestros(), _tabla_estados()],
        ddl_scripts=[
            DdlScript(
                id="DDL-001",
                order=1,
                name="01_tablas.sql",
                kind=DdlScriptKind.TABLES,
                engine=DbEngine.POSTGRESQL,
                statements=[_DDL_GUIAS, _DDL_SINIESTROS],
                sql=f"-- Tablas\n{_DDL_GUIAS};\n\n{_DDL_SINIESTROS};\n",
                source_refs=["TBL-001", "TBL-002"],
            ),
            DdlScript(
                id="DDL-002",
                order=2,
                name="02_indices.sql",
                kind=DdlScriptKind.INDEXES,
                engine=DbEngine.POSTGRESQL,
                statements=[
                    "CREATE INDEX ix_siniestros_estado_fecha "
                    "ON public.siniestros (estado_id, fecha_siniestro)"
                ],
                sql=(
                    "-- Índices\nCREATE INDEX ix_siniestros_estado_fecha "
                    "ON public.siniestros (estado_id, fecha_siniestro);\n"
                ),
                source_refs=["IDX-001"],
            ),
        ],
        seed_data=[
            SeedData(
                id="SEED-001",
                table_ref="TBL-003",
                table="siniestro_estados",
                reason="Catálogo de estados citado en el proceso PRO-001 del EF.",
                columns=["codigo", "nombre"],
                rows=[
                    {"codigo": "REGISTRADO", "nombre": "Registrado"},
                    {"codigo": "INVESTIGACION", "nombre": "En investigación"},
                    {"codigo": "CERRADO", "nombre": "Cerrado"},
                ],
                source_refs=["PRO-001"],
                evidence="Reportar, Registrar, Investigar, Recuperar, Cerrar",
                confidence=0.8,
                origin=Origin.STATED,
            )
        ],
        data_dictionary=[
            DictionaryEntry(
                id="DIC-0001",
                table="siniestros",
                column="fecha_siniestro",
                type="DATE",
                nullable=False,
                key="—",
                description="Fecha en que ocurrió el siniestro.",
                example="2026-03-14",
                source_refs=["FLD-002"],
                origin=Origin.STATED,
            ),
            DictionaryEntry(
                id="DIC-0002",
                table="siniestros",
                column="guia_id",
                type="BIGINT",
                nullable=False,
                key="FK",
                description="Guía sobre la que se reporta el siniestro.",
                example="8801",
                source_refs=["REL-001"],
                origin=Origin.DERIVED,
            ),
        ],
        er_diagram=ErDiagram(
            code=(
                "erDiagram\n"
                '  guias ||--o{ siniestros : "tiene"\n'
                '  siniestro_estados ||--o{ siniestros : "clasifica"'
            )
        ),
        design_decisions=[
            DesignDecision(
                id="DBD-001",
                title="Claves primarias subrogadas por identidad",
                decision=(
                    "Toda tabla de entidad lleva PK subrogada generada por el motor."
                ),
                rationale=(
                    "Las claves naturales del negocio (número de guía) cambian de "
                    "formato con el tiempo; se preservan como UNIQUE."
                ),
                alternatives_considered=["clave natural (numero de guía)"],
                consequences=[
                    "+ estabilidad ante cambios de formato del negocio",
                    "- requiere un índice único adicional por clave natural",
                ],
                scope=DecisionScope.GLOBAL,
                source_refs=["ADR-002"],
                confidence=0.8,
                origin=Origin.DERIVED,
            ),
            DesignDecision(
                id="DBD-002",
                title="Estado del siniestro normalizado como catálogo",
                decision="Los estados del siniestro viven en `siniestro_estados`.",
                rationale=(
                    "El EF enumera los estados del proceso PRO-001: un catálogo "
                    "permite añadir estados sin migrar el esquema."
                ),
                alternatives_considered=["columna de texto libre", "CHECK con enum"],
                consequences=["+ estados administrables", "- un JOIN en cada listado"],
                scope=DecisionScope.TABLE,
                table_refs=["TBL-003"],
                source_refs=["PRO-001"],
                confidence=0.75,
                origin=Origin.DERIVED,
            ),
        ],
        rule_mappings=[
            RuleMapping(
                id="RM-001",
                rule_ref="VAL-001",
                enforcement=RuleEnforcement.APPLICATION,
                table_ref="TBL-002",
                note=(
                    "«La fecha del siniestro no puede ser futura» compara con la "
                    "fecha actual: un CHECK con CURRENT_DATE no es determinista y "
                    "el motor lo rechaza. Se valida en la capa de aplicación."
                ),
                confidence=0.8,
                origin=Origin.DERIVED,
            ),
            RuleMapping(
                id="RM-002",
                rule_ref="BR-001",
                enforcement=RuleEnforcement.DECLARATIVE,
                constraint_ref="FK-001",
                table_ref="TBL-002",
                note="`guia_id NOT NULL` + FK impiden un siniestro sin guía.",
                confidence=0.9,
                origin=Origin.DERIVED,
            ),
        ],
        validation=DdlValidation(
            syntax_ok=True,
            engine=DbEngine.POSTGRESQL,
            validator="estructural+sqlglot",
            executed=False,
            checks={
                "all_fks_resolve": True,
                "all_tables_have_pk": True,
                "no_duplicate_names": True,
                "topological_order_ok": True,
                "types_in_engine_map": True,
                "identifiers_within_limits": True,
                "seed_respects_constraints": True,
            },
            errors=[],
            warnings=[],
        ),
        analysis=DatabaseAnalysis(
            risks=[
                Risk(
                    id="RISK-001",
                    description=(
                        "`siniestros` crece con cada evento reportado y el EF no "
                        "aporta volumetría: los índices se dimensionaron por "
                        "patrón de acceso, no por tamaño real."
                    ),
                    severity=RiskSeverity.MEDIA,
                    mitigation="Revisar el plan de ejecución con datos reales.",
                    source_ref="TBL-002",
                    confidence=0.6,
                    origin=Origin.DERIVED,
                )
            ],
            observations=[
                Observation(
                    id="OBS-001",
                    description=(
                        "VAL-001 no es expresable como CHECK determinista "
                        "(compara con la fecha actual)."
                    ),
                    reason="Se implementa en la capa de aplicación (Agente Backend).",
                )
            ],
            coverage=Coverage(
                entities_total=2,
                entities_mapped=2,
                uncovered_entity_refs=[],
                fields_total=2,
                fields_mapped=2,
                unmapped_field_refs=[],
                validations_total=1,
                validations_enforced=0,
                unenforced_validation_refs=["VAL-001"],
                rules_total=1,
                rules_enforced=1,
                unenforced_rule_refs=[],
            ),
        ),
        questions_for_dba=[
            DbaQuestion(
                id="Q-001",
                question=(
                    "¿Qué precisión y escala debe tener el monto del siniestro? "
                    "Se aplicó NUMERIC(12,2) por convención."
                ),
                reason=(
                    "El EF declara el monto sin precisión; afecta a COL-0006 de "
                    "`siniestros`."
                ),
                audience=Audience.TECNICO,
                blocking=False,
                linked_to_ref="COL-0006",
                confidence=0.6,
                origin=Origin.DERIVED,
            )
        ],
        metrics=DatabaseMetrics(
            tokens=TokenMetrics(input=4200, output=1800, total=6000),
            cost=0.039,
            duration=32.5,
            tables_total=3,
            columns_total=10,
            indexes_total=1,
            constraints_total=6,
            seed_rows_total=3,
            coverage=1.0,
            ddl_valid=True,
        ),
    )
