"""Contrato de datos del Agente QA (QaArtifact v1.0.0)."""

from ai.agents.api.schemas.enums import AuthScope
from ai.agents.arquitectura.schemas.enums import RiskSeverity
from ai.agents.ef.schemas.enums import Audience, Origin, QuestionStatus
from ai.agents.scrum.schemas.enums import MoscowPriority

from .artifact import (
    DEFAULT_MINUTES_BY_TYPE,
    DEFAULT_PRIORITY_FACTOR,
    MOSCOW_TO_PRIORITY,
    SCHEMA_VERSION,
    AuthCase,
    BoundaryAnchor,
    Coverage,
    Dataset,
    DatasetRow,
    ExecutionPlan,
    ExecutionTotals,
    QaAnalysis,
    QaArtifact,
    QaMetrics,
    QaQuestion,
    Risk,
    SourceRef,
    Suite,
    Target,
    TestCase,
    TestDatum,
    TestStep,
    TraceMatrix,
    TraceRow,
)
from .enums import (
    AnchorSource,
    AutomationHint,
    BoundaryKind,
    CoverageStatus,
    DataKind,
    TestCaseType,
    TestPriority,
)

__all__ = [
    "DEFAULT_MINUTES_BY_TYPE",
    "DEFAULT_PRIORITY_FACTOR",
    "MOSCOW_TO_PRIORITY",
    "SCHEMA_VERSION",
    "AnchorSource",
    "Audience",
    "AuthCase",
    "AuthScope",
    "AutomationHint",
    "BoundaryAnchor",
    "BoundaryKind",
    "Coverage",
    "CoverageStatus",
    "DataKind",
    "Dataset",
    "DatasetRow",
    "ExecutionPlan",
    "ExecutionTotals",
    "MoscowPriority",
    "Origin",
    "QaAnalysis",
    "QaArtifact",
    "QaMetrics",
    "QaQuestion",
    "QuestionStatus",
    "Risk",
    "RiskSeverity",
    "SourceRef",
    "Suite",
    "Target",
    "TestCase",
    "TestCaseType",
    "TestDatum",
    "TestPriority",
    "TestStep",
    "TraceMatrix",
    "TraceRow",
]
